server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidflorezrestrepo/microservices-with-spring-cloud
          search-paths:
          - 'ApplicationProperties'
          - 'ApplicationProperties/station*'
          #username: uname
          #password: passs